// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb4ZAS4xJCG_2cP-WN2FJqDXrEoDhQ23Y',
    appId: '1:193259975127:web:55213c45d77612669adb92',
    messagingSenderId: '193259975127',
    projectId: 'chat-app-eadb0',
    authDomain: 'chat-app-eadb0.firebaseapp.com',
    storageBucket: 'chat-app-eadb0.appspot.com',
    measurementId: 'G-RJSGN7NQEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-N8xAB-yayFDHzk-eacFZuON09S226o0',
    appId: '1:193259975127:android:bbe910beb55c29d29adb92',
    messagingSenderId: '193259975127',
    projectId: 'chat-app-eadb0',
    storageBucket: 'chat-app-eadb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOh1iPk6xC5IuOZGXIjqLmgQ3tcEMYYGo',
    appId: '1:193259975127:ios:4c316ddd9c3505149adb92',
    messagingSenderId: '193259975127',
    projectId: 'chat-app-eadb0',
    storageBucket: 'chat-app-eadb0.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOh1iPk6xC5IuOZGXIjqLmgQ3tcEMYYGo',
    appId: '1:193259975127:ios:4c316ddd9c3505149adb92',
    messagingSenderId: '193259975127',
    projectId: 'chat-app-eadb0',
    storageBucket: 'chat-app-eadb0.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb4ZAS4xJCG_2cP-WN2FJqDXrEoDhQ23Y',
    appId: '1:193259975127:web:6caa7bff307746519adb92',
    messagingSenderId: '193259975127',
    projectId: 'chat-app-eadb0',
    authDomain: 'chat-app-eadb0.firebaseapp.com',
    storageBucket: 'chat-app-eadb0.appspot.com',
    measurementId: 'G-Y37MWL16BJ',
  );

}